spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?stringtype=unspecified
    username: postgres
    password: postgres
  sql:
    init:
      mode: never
      username: postgres
      password: postgres
      schema-locations: classpath:db/schema-postgres.sql,classpath:db/schema-postgres-demo.sql
      data-locations: classpath:db/data-postgres.sql,classpath:db/data-postgres-demo.sql

s2:
  embedding:
    store:
      provider: PGVECTOR
      base:
        url: 127.0.0.1
      port: 5432
      databaseName: postgres
      user: postgres
      password: postgres
      dimension: 512